GET http://localhost:5148/

###

POST http://localhost:5148/customer-create
Content-Type: application/json

{
  "PartitionKey": "Smith1881",
  "RowKey": "John1881",
  "FirstName": "Smith1881",
  "LastName": "John1881"
}

###

POST http://localhost:5148/customer-list
Content-Type: application/json

{
  "PartitionKey": "Smith1881",
  "RowKey": "John1881"
}
